services:
  backend:
    build: .
    environment:
      - GOOGLE_API_KEY=AQ.Ab8RN6INT1vHzFu5m0RgIdFadNrr2OzevmBBlpwC_Jeezy3_OQ
  frontend:
    build: .
    command: streamlit run frontend.py --server.port 8501
    ports:
      - "8501:8501"
    depends_on:
      - backend


